version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  hello:
    docker:
      - image: circleci/welcome-config-image:0.2
    steps:
    - run: echo "Hello User"
  sleep:
    docker:
      - image: circleci/welcome-config-image:0.2
    steps:
    - run: sleep 5

workflows:
  Hello_Circle:  
    filters:
    branches:
      only:
        - test-circle-ci
    jobs:
      - hello
      - sleep
