version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

test-circle-ci-filter: &test-circle-ci-filter
  branches:
    only: /test-circle-ci/
  tags:
    ignore: /.*/

jobs:
  hello:
    docker:
      - image: circleci/welcome-config-image:0.2
    steps:
    - run: echo "Hello User"

  sleep:
    docker:
      - image: circleci/welcome-config-image:0.2
    steps:
    - run: sleep 5

workflows:
  version: 2

  hello-circle:  
    jobs:
      - hello:
        filters: *test-circle-ci-filter

      - sleep:
        requires:
          - hello
        filters: *test-circle-ci-filter
